### ISSUE TITLE
Model Download stuck at 0.0%

### ISSUE THREAD

**Issue by metalgie** [miaoshouai/miaoshouai-assistant#49] opened 2023-10-08 11:20 UTC
Hi,
   I'm trying to download some models, they are stuck at 0.0%! is there anything i need to do to get over this issue?

![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/36440920/27fc32a8-3983-4075-a36c-933ff04ce350)

regards

**Comment by triphop** [comment] 2023-10-11 09:28
on the branch of [bugfix/gradio_api_incompatibility](https://github.com/miaoshouai/miaoshouai-assistant/tree/bugfix/gradio_api_incompatibility) , I try to fix this issue, this branch passed my verification, you can have a try, and hope you give me the final result after your verification.

```sh
cd <your_stable_diffusion_directory>/extensions/miaoshouai-assistant/
git checkout -b verfication origin/bugfix/gradio_api_incompatibility
git pull --rebase -p
```
and then, please **restart webui**, hope everything goes well.

**Comment by metalgie** [comment] 2023-10-11 10:04
i can download now, but the speed is really snow (61.9M/151M [05:22<08:37, 172kbyte/s])

**Comment by triphop** [comment] 2023-10-12 03:27
thanks for your feedback, let's fix this issue about model download with slow speed.

**Comment by triphop** [comment] 2023-10-12 08:27
I have updated the branch mentioned above, please use the same branch to verify the download speed issue :)

**Comment by metalgie** [comment] 2023-10-12 12:23
> I have updated the branch mentioned above, please use the same branch to verify the download speed issue :)

download speed is back to normal. amazing work and response

**Comment by triphop** [comment] 2023-10-12 12:27
Since the issue is gone, let's close it.

**Comment by metalgie** [comment] 2023-10-12 12:28
will the branch will be changed from verification to main?

**Comment by metalgie** [comment] 2023-10-12 12:43
I started getting an issue with Automatic1111 UI, the extensions/ Installed tab it keeps loading and doesn't show any of the installed extensions, this issue happened after changing the branch to verification, could you have a look at it? thank you a lot of all the hard work your doing

**Comment by metalgie** [comment] 2023-10-12 12:43
I started getting an issue with Automatic1111 UI, the extensions/ Installed tab it keeps loading and doesn't show any of the installed extensions, this issue happened after changing the branch to verification, could you have a look at it? thank you a lot of all the challenging work you're doing

**Comment by triphop** [comment] 2023-10-12 12:48
Yes, verification branch has been merged into main branch. We'll try to reproduce the issue based on your feedback.
Many thanks.

**Comment by triphop** [comment] 2023-10-12 12:53
BTW, could you have try to move the `miaoshouai-assistant` directory to other location outside of automatic1111 directory and **reinstall miaoshouai-assistant** and to see whether the issue is still present?

**Comment by triphop** [comment] 2023-10-12 13:02
if the issue is still present after doing the above actions, please tell me the whole extensions under the `extensions folder`, this info will help me to address the issue.

**Comment by metalgie** [comment] 2023-10-12 13:26
I moved it out, i was able to load extensions tab, but after reinstalling it again, I got the same issue, here is the list of extensions folder:

sd-webui-infinite-image-browsing
sd-webui-animatediff
stable-diffusion-webui-wildcards
stable-diffusion-webui-rembg
sd-webui-3d-open-pose-editor
sd-extension-system-info
adetailer
sd_delete_button
sd-webui-ar
sd-webui-controlnet
sd-webui-deforum
sd-webui-mov2mov
canvas-zoom
miaoshouai-assistant

**Comment by triphop** [comment] 2023-10-13 03:32
I use the latest Automatic1111 and miaoshouai-assistant (integrated with our bugfix changes), and install all of the above extensions, I can successfully launch SD.

[screenshot](https://drive.google.com/file/d/1mougmH8g27IVQrF-OGfc27oNZa05wjKE/view?usp=sharing)

here is my extensions:
```sh
$ tree -L 1
.
├── adetailer
├── canvas-zoom
├── miaoshouai-assistant
├── put\ extensions\ here.txt
├── sd-extension-system-info
├── sd-webui-3d-open-pose-editor
├── sd-webui-animatediff
├── sd-webui-ar
├── sd-webui-controlnet
├── sd-webui-deforum
├── sd-webui-infinite-image-browsing
├── sd-webui-mov2mov
├── sd_delete_button
├── stable-diffusion-webui-rembg
└── stable-diffusion-webui-wildcards

14 directories, 1 file
```

did I miss any extension?

**Comment by metalgie** [comment] 2023-10-13 15:53
you didn't miss any extension, SD launch successfully for me, but accessing the Extensions tab is the issue:

![image](https://github.com/miaoshouai/miaoshouai-assistant/assets/36440920/b448b95f-1866-41f3-a572-253f9d7ae25f)


I only can see my installed extensions when i press check for updates:

<img width="674" alt="image" src="https://github.com/miaoshouai/miaoshouai-assistant/assets/36440920/23f63e16-c3ae-4085-a4fe-1a106a482b6b">

**Comment by metalgie** [comment] 2023-10-13 16:06
everything loads fine when i disable it:

<img width="643" alt="image" src="https://github.com/miaoshouai/miaoshouai-assistant/assets/36440920/4de15f55-e3f4-441a-8574-bb81cc127900">

**Comment by triphop** [comment] 2023-10-14 14:38
Thanks for your explaination of the issue, it is really weird, I should dig into it to find out root cause. keep in touch.

**Comment by triphop** [comment] 2023-10-16 02:54
so far, I cannot reproduce the same issue, [screenshot](https://drive.google.com/file/d/1mougmH8g27IVQrF-OGfc27oNZa05wjKE/view?usp=drive_link)

**Closed** 2023-11-15 07:47 UTC

**Comment by metalgie** [comment] 2023-11-19 19:58
I'm using Edge browser, which is causing this issue, is there anything you can do?
